// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repo

import (
	"github.com/shopspring/decimal"
)

type Category struct {
	ID   int64
	Name string
}

type Product struct {
	ID              int64
	CategoryID      int64
	Name            string
	Description     string
	Price           decimal.Decimal
	DiscountedPrice decimal.Decimal
}
